# Agenda

1. Threads + multiprocessing with `map`
2. `asyncio`
3. NumPy

In [1]:
# list comprehension

numbers = range(10)

[one_number ** 2
 for one_number in numbers]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [2]:

numbers = range(10)

[one_number ** 2               # expression ... what we used to use "map" for
 for one_number in numbers
 if one_number % 2]            # condition ... what we used to use "filter" for

[1, 9, 25, 49, 81]

In [5]:
# how does map work?

# we pass map two arguments:
# 1. a function that takes one argument
# 2. an iterable of data

words = 'this is a bunch of words'.split()

list(map(len, words))

[4, 2, 1, 5, 2, 5]

In [7]:
def count_vowels(s):
    total = 0

    for one_character in s:
        if one_character in 'aeiou':
            total += 1

    return total

words = 'this is a fantastic and enticing and superfabulous sentence'.split()

list(map(count_vowels, words))

[1, 1, 1, 3, 1, 3, 1, 6, 3]

In [9]:
print(*map(count_vowels, words))

1 1 1 3 1 3 1 6 3


# Exercise: Longest words

1. Write a function that takes a filename (string) as an argument, and returns the longest word found in that file.
2. Use the Executor.map functions (for threads and processes) to call this function on a list of filenames.
3. Print the longest words that you found.
4. Also: How much time does it take to run these? (You can use `time.time` to get the number of seconds since 1.1.70.)

In [10]:
import time
time.time()

1704269326.356544

# `asyncio`

Reactor model -- one process and one thread.

The way it works:
- We put all of our tasks (functions, basically) as elements on a list
- We run a `for` loop on the list, and let each function run a little bit
- When the function ends, we remove it from our list
- We can always add new functions
- So long as there are tasks on the list, we re-run our `for` loop from the start

## Advantages
- Many more items can run
- We don't have to worry about thread safety
- We know exactly when a function might be stopped
- We have access to global variables

## Disadvantages
- No real I/O
- We don't really, directly run our function
- We add two words to Python's vocabulary:
    - `async` -- `async def` creates a function that can be run via the event loop
    - `await` -- very similiar to `yield`, in that it says: Whatever is to my right will take a long time, so I'll go to sleep waiting for it

# Next up:

- More `asyncio`
- NumPy

Resume at 11:20

# Terms

- `async def` -- syntax used in Python to create a function that, when run, gives us a coroutine back
- coroutine -- the body of a function, along with its stack frame, that we get back from running an `async def`. We can run a coroutine directly with `asyncio.run` or by putting it to the right of `await`.
- task -- a wrapper for a coroutine, placed on the event loop, and executed whenever the event loop wants.

If I really want to see things run concurrently, then I need to:
- Create several tasks, based on coroutines
- Run all of the tasks as a group



# NumPy

NumPy array:
- Python API
- C implementation



In [11]:
import numpy as np

In [12]:
# np.nparray is the data structure we want
# but we'll build it with np.array, passing it a list

a = np.array([10, 20, 30, 40, 50, 60])
a

array([10, 20, 30, 40, 50, 60])

In [13]:
# many standard Python things work with a NumPy array

a[0]

10

In [14]:
a[1]

20

In [15]:
a[-1]

60

In [17]:
a[2:5]

array([30, 40, 50])

In [18]:
for one_item in a:
    print(one_item)

10
20
30
40
50
60


In [19]:
# some other ways to create NumPy arrays

a = np.random.randint(0, 100, 10)    # 10 ints from 0-100
a

array([12, 25, 33, 61, 32, 52, 97, 91, 40, 66])

In [20]:
a = np.random.rand(10)   # 10 floats from 0-1
a

array([0.29683241, 0.93433433, 0.84712284, 0.47561611, 0.74451551,
       0.85910408, 0.86507627, 0.50345427, 0.43890329, 0.6056343 ])

In [21]:
a = np.arange(20)   # all numbers from 0-19
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# fancy indexing -- I can request multiple indexes

a = 